### ISSUE TITLE
Add KV Store for holding queue

### ISSUE THREAD

**Issue by jonfriesen** [MegaMakers/amplifyBot#1]
Currently we use a simple object for storing recent posts. If the server is reset/crashes this data is lost. We should look into using a javascript built in KV Store to persist our values.

Something similar to bolt for Go https://github.com/boltdb/bolt

**Comment by vineet-sinha** [comment]
I did some research on this - and here are the different options I see.

**NeDB**: [npm](https://www.npmjs.com/package/nedb)
- Subset of MongoDB features
- `-` Not maintained (see NestDB)

**NestDB**:  [npm](https://www.npmjs.com/package/nestdb)
- Most active fork of NeDB
- `-` Only 3 public releases (once per year)
- `-` Small number of stars on the project - perhaps because they are all on NeDB

**[PouchDB](https://pouchdb.com/)**:  [npm](https://www.npmjs.com/package/pouchdb)
- Works very well with CouchDB
- Great for offline use and then syncs with another database.
- `-` Really a wrapper of other databases (CouchDB, IndexedDB in Browsers, LevelDB in Nodejs)

**Level**:  [npm](https://www.npmjs.com/package/level)
- Pure KV support
- Interface to LevelDB (C++ DB by Google)
- Seems to target features to align with the browser standard IndexedDB
- `-` No support for queries beyond a get

**[RocksDB](https://rocksdb.org/)**:  [npm](https://www.npmjs.com/package/level-rocksdb)
- Pure KV support
- LevelDB compliant multi-CPU optimized DB (built by FB)
- `-` No support for queries beyond a get

**[SQLite](https://sqlite.org/index.html)**: [npm](https://www.npmjs.com/package/sqlite)
- `+` Supports complex queries
- `-` Slower than LevelDB

**LowDB**: [npm](https://www.npmjs.com/package/lowdb)
- `+` Pure JS
- `?` Lodash based
- `+` and extremely popular
- `-` Likely scales worst among other options - seems like a great in memory API for small collection with a read/write adaptor.

**Loki**: [npm](https://www.npmjs.com/package/lokijs)
- `+` Pure JS
- `+` As popular as Level, SQLite, LowDB
- `+` More performant than LowDB.
- `+` Supports complex queries
- `-` Likely slower than LevelDB and SQLite.

npm links above are to the promise aware javascript library.

I don't have any biases after doing this research. Feel free to share any thoughts.

Our needs do not need complex queries, so I am gravitating towards trying LevelDB.

**Comment by jonfriesen** [comment]
this is gold! thanks @vineet-sinha
