### ISSUE TITLE
The bot tweets even if I say "No, thank you"

### ISSUE THREAD

**Issue by Merott** [MegaMakers/amplifyBot#20]
At least in my case it happened. This was my Slack message:

> I tweet a progress update every Thursday, for accountability, and here comes this week’s! I appreciate you even looking at it for two seconds :eyes: — if you can give it some Twitter love :heart: too, then I love you even more! :heart_eyes:
https://twitter.com/Merott/status/1215323784942686208

The bot asked if I want it to tweet that for me, and I clicked "No, thank you." but it was tweeted anyway (after 3 reactions.)

![image](https://user-images.githubusercontent.com/1757708/72173587-d3083a00-33cf-11ea-8362-2768e5b6750b.png)

**Comment by vineet-sinha** [comment]
Thanks @Merott for flagging this. It should be fixed now, but please let me know if the issue comes up again.

Interestingly enough the fix was already done yesterday when adding a different feature, I had just not deployed it as I was still testing it. I am glad that the fix resolved two issues :-) 

Ref: dc77bab962ef890d5bb65e3ba16665cea0c97e3a and d14f1fc6796b855055b9079465611a0b51d24f3c
